'use client';

import { useState, useMemo, useEffect } from 'react';
import { X, Trash2, Star, Download, Save, FolderOpen, Search, Code2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { SavedCodeItem } from '@/types/python';
import { formatTimestamp, truncateCode } from '@/lib/python-utils';

interface SavedCodesModalProps {
  isOpen: boolean;
  onClose: () => void;
  codes: SavedCodeItem[];
  isLoading: boolean;
  onSave: (title: string, code: string) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
  onToggleImportant: (id: string) => Promise<void>;
  onSelect: (code: string) => void;
  currentCode: string;
  initialShowSaveInput?: boolean;
}

export function SavedCodesModal({
  isOpen,
  onClose,
  codes,
  isLoading,
  onSave,
  onDelete,
  onToggleImportant,
  onSelect,
  currentCode,
  initialShowSaveInput,
}: SavedCodesModalProps) {
  const [filter, setFilter] = useState<'all' | 'important'>('all');
  const [saveTitle, setSaveTitle] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [showSaveInput, setShowSaveInput] = useState(initialShowSaveInput || false);
  const [searchQuery, setSearchQuery] = useState('');

  // Reset or set states when modal opens
  useEffect(() => {
    if (isOpen) {
      setShowSaveInput(initialShowSaveInput || false);
      setSaveTitle('');
    }
  }, [isOpen, initialShowSaveInput]);

  const filteredCodes = useMemo(() => {
    let result = codes;
    if (filter === 'important') result = result.filter(c => c.isImportant);
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(c => c.title.toLowerCase().includes(q) || c.code.toLowerCase().includes(q));
    }
    return result;
  }, [codes, filter, searchQuery]);

  const handleSave = async () => {
    if (!currentCode.trim()) return;
    setIsSaving(true);
    await onSave(saveTitle || `Code ${new Date().toLocaleString()}`, currentCode);
    setSaveTitle('');
    setShowSaveInput(false);
    setIsSaving(false);
  };

  const handleDownloadPDF = () => {
    const codesToExport = filter === 'important' ? codes.filter(c => c.isImportant) : codes;
    if (codesToExport.length === 0) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
<!DOCTYPE html>
<html>
<head>
  <title>My Saved Codes — Knobly Python Lab</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #1e293b; background: #fff; }
    .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #6366f1; }
    .header h1 { font-size: 28px; color: #312e81; margin-bottom: 4px; }
    .header p { font-size: 13px; color: #64748b; }
    .code-block { margin-bottom: 30px; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; page-break-inside: avoid; }
    .code-header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 12px 20px; display: flex; justify-content: space-between; align-items: center; }
    .code-header h3 { font-size: 15px; font-weight: 700; }
    .code-header .meta { font-size: 11px; opacity: 0.85; }
    .code-header .star { color: #fbbf24; margin-left: 8px; }
    .code-body { padding: 16px 20px; background: #f8fafc; }
    .code-body pre { font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace; font-size: 13px; line-height: 1.6; white-space: pre-wrap; word-break: break-all; color: #334155; }
    .footer { text-align: center; margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
    @media print { body { padding: 20px; } .code-block { break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>🐍 My Saved Codes</h1>
    <p>Knobly Python Lab • ${filter === 'important' ? 'Important Codes' : 'All Codes'} • ${codesToExport.length} code${codesToExport.length !== 1 ? 's' : ''} • ${new Date().toLocaleDateString()}</p>
  </div>
  ${codesToExport.map((c, i) => `
    <div class="code-block">
      <div class="code-header">
        <h3>#${i + 1} ${c.title}${c.isImportant ? ' <span class="star">⭐</span>' : ''}</h3>
        <span class="meta">${new Date(c.createdAt).toLocaleDateString()}</span>
      </div>
      <div class="code-body">
        <pre>${c.code.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</pre>
      </div>
    </div>
  `).join('')}
  <div class="footer">Generated by Knobly Python Lab — knoblyweb.in</div>
</body>
</html>`;

    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[200]"
          />
          <motion.div
            initial={{ scale: 0.92, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.92, opacity: 0 }}
            transition={{ type: 'spring', damping: 25, stiffness: 350 }}
            className="fixed inset-4 md:inset-auto md:top-[5%] md:left-1/2 md:-translate-x-1/2 md:w-[600px] md:max-h-[90vh] bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-2xl z-[201] overflow-hidden shadow-2xl shadow-indigo-500/10 flex flex-col"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--border-color)] bg-gradient-to-r from-purple-600 to-indigo-600 shrink-0 shadow-sm relative overflow-hidden">
              <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-10 pointer-events-none"></div>
              <div className="flex items-center gap-3 relative z-10">
                <div className="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center backdrop-blur-md border border-white/30 shadow-inner">
                  {/* Real yellow folder SVG */}
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" className="w-6 h-6 drop-shadow-md">
                    <path fill="#FFCA28" d="M20,6h-8l-2-2H4C2.9,4,2.01,4.9,2.01,6L2,18c0,1.1,0.9,2,2,2h16c1.1,0,2-0.9,2-2V8C22,6.9,21.1,6,20,6z"/>
                    <path fill="#FFD54F" d="M20,8H4v10h16V8z"/>
                  </svg>
                </div>
                <div>
                  <h2 className="text-[16px] font-black tracking-wide drop-shadow-sm !text-white !opacity-100 m-0">My Saved Codes</h2>
                  <span className="text-[11px] font-semibold !text-white/90 m-0 block">{codes.length} code{codes.length !== 1 ? 's' : ''} saved</span>
                </div>
              </div>
              <div className="flex items-center gap-3 relative z-10">
                <button
                  onClick={handleDownloadPDF}
                  disabled={codes.length === 0}
                  className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-[13px] font-bold !bg-red-600 !text-white shadow-[0_4px_16px_rgba(239,68,68,0.5)] border border-red-500 hover:!bg-red-700 hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 disabled:shadow-none"
                  title="Download as PDF"
                >
                  <Download className="w-4 h-4" />
                  <span>PDF</span>
                </button>
                <button
                  onClick={onClose}
                  className="p-2 rounded-xl !bg-black/20 hover:!bg-black/30 transition-all backdrop-blur-md border border-white/10 hover:border-white/30 shadow-sm flex items-center justify-center group"
                  title="Close"
                >
                  <X className="w-5 h-5 !text-white !stroke-white group-hover:scale-110 transition-transform stroke-[2.5]" />
                </button>
              </div>
            </div>

            {/* Save New + Search + Filters */}
            <div className="px-5 py-3 border-b border-[var(--border-color)] space-y-3 shrink-0">
              {/* Save New Code */}
              {showSaveInput ? (
                <div className="flex items-center gap-2">
                  <input
                    type="text"
                    value={saveTitle}
                    onChange={e => setSaveTitle(e.target.value)}
                    placeholder="Code title (e.g. Fibonacci Series)"
                    className="flex-1 bg-[var(--glass-bg)] border border-[var(--border-color)] rounded-lg px-3 py-2 text-xs text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:outline-none focus:border-[var(--accent-primary)]/50"
                    autoFocus
                    onKeyDown={e => e.key === 'Enter' && handleSave()}
                  />
                  <button
                    onClick={handleSave}
                    disabled={isSaving || !currentCode.trim()}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold bg-[var(--accent-primary)] text-white hover:opacity-90 transition-opacity disabled:opacity-40"
                  >
                    <Save className="w-3.5 h-3.5" />
                    {isSaving ? '...' : 'Save'}
                  </button>
                  <button
                    onClick={() => { setShowSaveInput(false); setSaveTitle(''); }}
                    className="p-2 rounded-lg text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--glass-bg)] transition-colors"
                  >
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ) : (
                <button
                  onClick={() => setShowSaveInput(true)}
                  disabled={!currentCode.trim()}
                  className="w-full flex items-center justify-center gap-2 py-2 rounded-lg border-2 border-dashed border-[var(--border-color)] hover:border-[var(--accent-primary)]/50 text-xs text-[var(--text-muted)] hover:text-[var(--accent-primary)] transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                >
                  <Save className="w-3.5 h-3.5" />
                  Save Current Code
                </button>
              )}

              {/* Search + Filters Row */}
              <div className="flex items-center gap-2">
                <div className="flex-1 relative">
                  <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-[var(--text-muted)]" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={e => setSearchQuery(e.target.value)}
                    placeholder="Search codes..."
                    className="w-full bg-[var(--glass-bg)] border border-[var(--border-color)] rounded-lg pl-8 pr-3 py-1.5 text-xs text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:outline-none focus:border-[var(--accent-primary)]/50"
                  />
                </div>
                <div className="flex bg-[var(--glass-bg)] border border-[var(--border-color)] rounded-lg overflow-hidden">
                  <button
                    onClick={() => setFilter('all')}
                    className={`px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-colors ${filter === 'all' ? 'bg-[var(--accent-primary)]/20 text-[var(--accent-primary)]' : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'}`}
                  >
                    All
                  </button>
                  <button
                    onClick={() => setFilter('important')}
                    className={`px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider transition-colors flex items-center gap-1 ${filter === 'important' ? 'bg-amber-500/20 text-amber-400' : 'text-[var(--text-muted)] hover:text-[var(--text-primary)]'}`}
                  >
                    <Star className="w-3 h-3" /> Important
                  </button>
                </div>
              </div>
            </div>

            {/* Code List */}
            <div className="flex-1 overflow-y-auto p-4 space-y-2.5">
              {isLoading ? (
                <div className="flex items-center justify-center h-40">
                  <div className="flex flex-col items-center gap-3">
                    <div className="w-6 h-6 border-2 border-[var(--accent-primary)] border-t-transparent rounded-full animate-spin" />
                    <span className="text-xs text-[var(--text-muted)]">Loading codes...</span>
                  </div>
                </div>
              ) : filteredCodes.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-40 text-center">
                  <Code2 className="w-10 h-10 text-[var(--text-muted)] mb-3 opacity-40" />
                  <p className="text-xs text-[var(--text-secondary)]">
                    {codes.length === 0 ? 'No codes saved yet' : filter === 'important' ? 'No important codes' : 'No matching codes'}
                  </p>
                  <p className="text-[10px] text-[var(--text-muted)] mt-1">
                    {codes.length === 0 ? 'Save your code to see it here' : 'Try changing your search or filter'}
                  </p>
                </div>
              ) : (
                filteredCodes.map((item) => (
                  <motion.div
                    key={item.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="group p-3 bg-[var(--glass-bg)] hover:brightness-110 rounded-xl border border-[var(--glass-border)] hover:border-[var(--accent-primary)]/40 transition-all cursor-pointer"
                    onClick={() => { onSelect(item.code); onClose(); }}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1.5">
                          {item.isImportant && <Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400 shrink-0" />}
                          <span className="text-xs font-semibold text-[var(--text-primary)] truncate">{item.title}</span>
                          <span className="text-[9px] text-[var(--text-muted)] shrink-0">{formatTimestamp(item.createdAt)}</span>
                        </div>
                        <pre className="text-[11px] text-[var(--text-secondary)] font-mono leading-relaxed truncate whitespace-pre-wrap line-clamp-2">
                          {truncateCode(item.code, 2)}
                        </pre>
                      </div>
                      <div className="flex items-center gap-1 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={e => { e.stopPropagation(); onToggleImportant(item.id); }}
                          className={`p-1.5 rounded-lg transition-colors ${item.isImportant ? 'text-amber-400 hover:bg-amber-500/20' : 'text-[var(--text-muted)] hover:text-amber-400 hover:bg-amber-500/10'}`}
                          title={item.isImportant ? 'Remove from important' : 'Mark as important'}
                        >
                          <Star className={`w-3.5 h-3.5 ${item.isImportant ? 'fill-amber-400' : ''}`} />
                        </button>
                        <button
                          onClick={e => { e.stopPropagation(); onDelete(item.id); }}
                          className="p-1.5 rounded-lg text-[var(--text-muted)] hover:text-red-400 hover:bg-red-500/10 transition-colors"
                          title="Delete"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  </motion.div>
                ))
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
